language: java

jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - secure: CLZmelvF+zmvNUaAO0ohh3YJUw1hunZ/CPkVBlxCymKzSZKjwnHzVqrlulbOd+yuym61FXSpu3lWi90tSrnB2Lm9wX3uWW82YtIgr9wXJLwnCoxw0vUWclrsxNyZmjknXrrtPZ/R4vstro/NqG7d1VZ/9Sm5PKPp4zM16ucmG3TljVs5Q6di4Z/Mueurubti2ADODipeDwzuMZVOyndPpCtz92kuGrDGtw4+6HY2Y6hhmOcDUzuq7j91fd42uB3TynbwojqO3qDsT+/XqqJpTrGXpr6g9VaACcENK+vdLN9B72P4MwAcs7oimBJZH/qOD0PESvT21kK80i2Yqmh4Fq9NCWjPHPKKMoF2vqkq4AZBBw7B9BFi/G6qD5CFULZSjAKlSyptuosYIdOhvJSgmshNB67y2Pn8Y8z0XPdiwxYJerfmtuZ38ynYmHywXHkPMdlmMcNVPJ5Dw4LrEbi3WTIN/BnExfB/viBzGD31B46mB2AX09yLcIkN3vOYJ2DwCtKX5WNPum2eWoX766PlXoX4MRf76Ldp4ujyXdGq0r8fKHz2C1iJPXtCZAtw/2m8c2V5B4RoFcQN6FCJ8hp986VMTHktdpCZPpHIuqrC6SJusGKEsks2N/JCrJR+ShfV+dOaLWMBiZ34yBpjzc3melShlYGAr/V/3bSkzKwWCqo=
    - secure: Wg6+GQohN/z/x0/Ew8CeTuKrGzFgovnG2ZQGozhC82Q8aaoQgWJ+z5p67WUo2/n0bsIeTvyE63mvnKOt5+3dZwCV+2keg8iX9g7qN9GMF0s8XP/Dt0YfJ/hFgsQf0By8mHQAAPfX8D0yUf/gZkfxLl20qMPd9Sk/E2ATxIlYGUKtJxKbmnjIrI3NoYvWnn6UDHn3JjdCfyd0gH4rWd6smR53aQ7FePN/ZbisfrWCe0b1p0qagY6G8rjAHwBXXOc1Z98MDdAPniEtnVi5TNYDKYRVIZARYUgACAzICJgr4AlcEzhuPSIIlivEMIpOfFtl1MDgO7tp35SkNfvJeZxwhXvQtHoKon+CX7p8SMCy9/8qnYyqIFrzoFdtaePJlC+FchGJ2H4sTuTgeAjSdqd4QacKcxvRyxPG7VkV6KlK3UGTek3hrI+vVZ72W/LUJp7W5oKS99kTUwEcgKfmwzftXc2aNbdrKeVFd5lh4QRhy55Ka2mNADUhiOvjSF+Vw6WfY3RRRvH7Eb3OSFFOS2YXELrxCgEpTcPuksrlxz3gE/u73y2tywzp6MEKvHOO5wOorHajAuCCKcCqE2xZRdVWKMoQI0GYtRi/TW3o14DhOCLez3iSD5nv4BCGiEz8Mb3EODNKU+lB5OUTbdVqjpN0RVy0gB8E3EfArWHPAaw8kCc=

after_sucess:
  - chmod +x ./publish.sh; ./publish.sh